---
title: "Example file for `{devoirs}` system"
date: 2024-05-30
author: Danny Kaplan
crossref:
  custom:
    - key: qst
      kind: float
      reference-prefix: "Question"
---

```{r include=FALSE}
library(devoirs)
```


```{r echo=FALSE, results="asis"}
devoirs_start(collectURL =
"https://docs.google.com/forms/d/e/1FAIpQLSevJgyHTRHm6_HVQqrYMd8wjMYifPknPLXtpVTunlWlO7RbMw/viewform?usp=pp_url")
```




::: {.callout-note #qst-blue-moon}
## 

What color is the blue moon? <!-- Use {mcqdebug} to capture options to file. -->

```{mcq}
#| label: first-one
#| inline: true
#| show_hints: true
1. blue [hint: It's not blue!]
2. red $\sqrt{3}$
3. moon colored [correct]
```

What is the moon made of?

```{mcq}
#| label: second-one
1. Blue cheese [hint: Sorry!]
2. Stilton [hint: Nice cheese, but not the right answer]
3. Moon rocks [correct hint: Good job]
```

:::

`r getwd()`

::: {.callout-note #qst-my-essay}
##

Write something of interest!

`r devoirs_text("of-interest")`
:::

<!-- PROVIDING THE devoirs.js file -->

<!-- YOU MUST INCLUDE THIS to make the items responsive -->

<!-- while debugging devoirs.js, include this way ... -->
<!--script type="text/javascript" src="devoirs.js"></script-->
<!-- otherwise, include text from package -->
`r devoirs_end()`
