## Section [Section-1]


aparker@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-05 23:35:58) [score = none]

: today's class encouraged us to think about how each and every question can be thought of quantitatively. We talked about how the goal of this class is to create models and understand what models are: systems consisting of components that relate to each other. One thing that I found particularly useful was thinking of equations as books in a library--a tool that can be whipped out to understand the "real world" in a quantitative way. I really quite liked that. I also greatly appreciate the enthusiasm and the desire to make math feel accessible and meaningful to us all. 



byoungstrom@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-05 11:20:10) [score = none]

: I learned that my professor was in the navy, clarified what a model was, the different ways quantitative reasoning can be applied to seemingly unrelated questions, and about the SIR model.



cposey@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-05 13:24:58) [score = none]

: In this class we defined 'model' as 'objects in relationship meant to correspond to reality'. I found the use of models in running a submarine interesting, and would like to know more details.



croll@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-05 20:02:48) [score = none]

: Introductions, Administrative and operational summary, expectations, and foundational concepts to get the class started.



druth@uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-05 09:34:03) [score = none]

: DMR pre-class test



elau@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-05 11:37:10) [score = none]

: From our Monday session this week, I learned that it's often the job of someone who employs quantitative thinking not just to execute such thought, but to argue for it's use in situations where it might be justified. I imagine the scientist here as an advocate for unbiased objectivity. Although numbers can be used dishonestly, I found it encouraging to imagine the class as a way to think without bias. 



jrubocki@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-05 11:20:41) [score = none]

: I learned about the SIR model and also a good concrete definition of models that create a relationship that corresponds to reality.



lbradley@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-05 16:29:36) [score = none]

: Good intro to the class, cleared up a lot of questions I had about what it was going to be. Mainly took away the idea of what a model is and how we're mainly going to be dealing with that in contrast to what we did in QR2. SIR was a takeaway as well



lzuckerman@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-06 13:15:45) [score = none]

: In this class we reviewed the syllabus, discussed the ways in which different questions can be answered quantitatively, came to an understanding of what a model is (objects in relationship meant to correspond to reality), and looked at ways in which patterns of covid infections can be modeled on a graph.



mmeegan@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-05 20:23:43) [score = none]

: We went over what models are, specifically involving objects in relationship meant to correspond to reality. We also went over the example of the SIR model in the context of COVID. I think it was most meaningful to connect mathematical modeling to real-world modeling. One thing that I am still slightly confused about is what precisely we are learning in this class and how it relates to QRII. However, I also do believe that this will become more clear as we go.



mshetty@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-05 19:36:47) [score = none]

: I learned a lot about Dean Ruth, and his past experience with the navy. We learned a bit about what quant. reasoning actually is, and how it can be applied to almost any situation. We also talked about a SIR (susceptable, infected, recovered) model. 



rleschber@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-05 17:52:38) [score = none]

: That this course is to be focused on the internal workings of functions that we took for granted in Qnt 2. Also, that we will learn to see the quantitative side of things that might not be so obvious otherwise.



ddonahoo@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



jjun@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



jpeery@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



rharris@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



rlin@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



smcclure@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



## Section [Section-3]


calbright@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-06 15:54:37) [score = none]

: This was a nice introduction to the class. The concepts seem easily accessible, and I liked how we tied models/math to the real world. No criticisms or complaints.



csmith@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-06 17:00:01) [score = none]

: On our first class session, we did brief introductions, and discussed the syllabus and where quantitative thinking is seen and used in everyday life. We discussed models and examples of them. This was the most meaningful/interesting part of class, as the explanation of how useful and how widely applied models are was engaging, especially when runway models were given as an example. As someone who doesn't necessarily think in "math terms", this made the concept easier to grasp!



dlaster@student.uaustin.org
: (One-minute:1-min-week1-a @ 2026-01-06 15:46:19) [score = none]

: Today in class we did introductions both personally and about the course before jumping in to discussing models and how most things have some quantitative measurable value to the, even foreign policy and beauty in nature. Models are used to show the way something could potentially work or be used, such as how a runway model shows how clothes could look and an architectural model shows small scale buildings to fix any issues before going large scale. A financial model and predict finances and investment quality.



cfishman@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



cniczyporuk@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



cvalentine@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



ddickmann@uaustin.org
: (NA:NA @ NA) [score = none]

: NA



eulloa@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



gnelson@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



hplane@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



lbutler@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



lsowers@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



nmikhael@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



sharvey@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



ssanders@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



ssuthar@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



## Section [Section-4]


ashor@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



cblythe@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



cwhitmire@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



cwiese@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



eborovsky@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



ggretencord@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



gguillen@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



jcrawford@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



jstrauss@uaustin.org
: (NA:NA @ NA) [score = none]

: NA



lcarr@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



mcronin@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



mraymond@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



nrobertson@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



santhony@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA



sportesi@student.uaustin.org
: (NA:NA @ NA) [score = none]

: NA

